# Generated by Django 5.2 on 2025-12-14 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Evento')),
                ('descricao_curta', models.CharField(max_length=500, verbose_name='Descrição Curta')),
                ('descricao_completa', models.TextField(verbose_name='Descrição Completa')),
                ('banner_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do Banner/Capa do Evento')),
                ('local_endereco', models.CharField(max_length=255, verbose_name='Endereço Físico')),
                ('local_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do Mapa/Local (Ex: Google Maps)')),
                ('data_inicio', models.DateTimeField(verbose_name='Data e Hora de Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data e Hora de Fim')),
                ('prazo_inscricao', models.DateTimeField(verbose_name='Prazo Final de Inscrição')),
                ('tipo', models.CharField(choices=[('gratuito', 'Gratuito'), ('pago', 'Pago')], default='gratuito', max_length=10, verbose_name='Tipo (Pago/Gratuito)')),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço (R$)')),
                ('capacidade', models.PositiveIntegerField(default=0, verbose_name='Capacidade Máxima de Participantes')),
                ('exige_aprovacao', models.BooleanField(default=False, verbose_name='Exige aprovação manual do organizador?')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='rascunho', max_length=15, verbose_name='Status do Evento')),
                ('categoria', models.CharField(choices=[('tecnologia', 'Tecnologia e TI'), ('negocios', 'Negócios e Empreendedorismo'), ('saude', 'Saúde e Bem-estar'), ('entretenimento', 'Entretenimento e Lazer'), ('esportes', 'Esportes e Fitness'), ('outros', 'Outros')], default='outros', max_length=30, verbose_name='Categoria')),
                ('mostrar_participantes', models.BooleanField(default=True, verbose_name='Mostrar lista parcial de participantes no Feed?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_organizados', to=settings.AUTH_USER_MODEL, verbose_name='Organizador')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data_inicio'],
            },
        ),
    ]
