# Generated by Django 5.2 on 2025-12-14 21:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente (Aguardando Aprovação/Pagamento)'), ('aprovada', 'Aprovada/Confirmada'), ('recusada', 'Recusada'), ('cancelada', 'Cancelada pelo Participante')], default='pendente', max_length=15, verbose_name='Status da Inscrição')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Inscrição')),
                ('codigo_verificacao', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código Único de Check-in')),
                ('check_in_realizado', models.BooleanField(default=False, verbose_name='Check-in Realizado')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='events.evento', verbose_name='Evento Inscrito')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_feitas', to=settings.AUTH_USER_MODEL, verbose_name='Participante')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['data_inscricao'],
                'unique_together': {('participante', 'evento')},
            },
        ),
    ]
